---
title: "220 Project"
author: "Alex Fan"
date: "11/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)
dat <- read_csv("dat.csv")
```

```{r}
head(dat)

dat$age2 <- dat$age^2
dat$srvlng2 <- dat$srvlng^2
dat$rgroup <- factor(dat$rgroup)
prop.table(table(dat$rgroup))
levels(dat$rgroup) <- c("None", "Protestant", "Catholic", "Other Christian", "Other religion")
dat$rgroup <- factor(dat$rgroup, levels = c("Protestant", "None", "Catholic", "Other Christian", "Other religion"))
datNOW <- dat %>%
  filter(congress == 105)

summary(datNOW)
lm.1 <- lm(nowtot ~ ngirls + female + white + repub + age + age2 + srvlng + srvlng2 + rgroup + demvote + totchi + region, data = datNOW)
summary(lm.1)

head(datNOW)
library(plm)
plm(nowtot ~ ngirls + female + white + repub + age + age2 + srvlng + srvlng2 + rgroup + demvote,
                    data = datNOW,
                    index = c("totchi"), 
                    model = "within")
```


